/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    categories: Category;
    'rich-content': RichContent;
    'news-feed': NewsFeed;
    questions: Question;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'rich-content': RichContentSelect<false> | RichContentSelect<true>;
    'news-feed': NewsFeedSelect<false> | NewsFeedSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ko' | 'en') | ('ko' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: 'ko' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  legacySourceUrl?: string | null;
  legacyObjectKey?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  legacyUrl?: string | null;
  contentHTML?: string | null;
  seoDescription?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rich-content".
 */
export interface RichContent {
  id: number;
  content?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-feed".
 */
export interface NewsFeed {
  id: number;
  title: string;
  slug: string;
  category:
    | 'property-info'
    | 'austin-news'
    | 'resources/school'
    | 'resources/koreanbusiness'
    | 'resources/tours'
    | 'resources/gallery';
  legacy_category?: string | null;
  legacyId?: string | null;
  /**
   * Assign the legacy menu/board for restored navigation and filtering.
   */
  legacyBoardId?:
    | (
        | 'legacy-board-1'
        | '1'
        | 'legacy-board-2'
        | '2'
        | 'legacy-board-3'
        | '3'
        | 'legacy-board-4'
        | '4'
        | 'legacy-board-5'
        | '5'
        | 'legacy-board-6'
        | '6'
        | 'legacy-board-7'
        | '7'
        | 'legacy-board-8'
        | '8'
        | 'legacy-board-9'
        | '9'
        | 'legacy-board-10'
        | '10'
        | 'legacy-board-11'
        | '11'
        | 'legacy-board-12'
        | '12'
        | 'legacy-board-13'
        | '13'
        | 'legacy-board-14'
        | '14'
        | 'legacy-board-15'
        | '15'
      )
    | null;
  legacyUrl?: string | null;
  /**
   * Migrated legacy HTML content.
   */
  legacyContent?: string | null;
  /**
   * Optional raw HTML source for new posts.
   */
  rawContent?: string | null;
  /**
   * Compose the article with formatting and R2-backed media uploads.
   */
  richContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt: string;
  legacyViewCount: number;
  viewCount: number;
  readCount: number;
  legacyAuthor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  subject: string;
  message: string;
  name: string;
  email: string;
  phone?: string | null;
  publishedAt?: string | null;
  viewCount: number;
  legacyId?: string | null;
  legacyUrl?: string | null;
  legacyContentHTML?: string | null;
  legacyAuthor?: string | null;
  status: 'new' | 'in-progress' | 'resolved';
  answer?: string | null;
  answeredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'rich-content';
        value: number | RichContent;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  legacySourceUrl?: T;
  legacyObjectKey?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  legacyUrl?: T;
  contentHTML?: T;
  seoDescription?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rich-content_select".
 */
export interface RichContentSelect<T extends boolean = true> {
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-feed_select".
 */
export interface NewsFeedSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  legacy_category?: T;
  legacyId?: T;
  legacyBoardId?: T;
  legacyUrl?: T;
  legacyContent?: T;
  rawContent?: T;
  richContent?: T;
  publishedAt?: T;
  legacyViewCount?: T;
  viewCount?: T;
  readCount?: T;
  legacyAuthor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  subject?: T;
  message?: T;
  name?: T;
  email?: T;
  phone?: T;
  publishedAt?: T;
  viewCount?: T;
  legacyId?: T;
  legacyUrl?: T;
  legacyContentHTML?: T;
  legacyAuthor?: T;
  status?: T;
  answer?: T;
  answeredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Homepage hero background. The site gradient overlay remains applied automatically.
   */
  heroImage?: (number | null) | Media;
  /**
   * Upload multiple homepage hero images. One is selected randomly per visit; the gradient overlay remains applied.
   */
  heroImages?: (number | Media)[] | null;
  /**
   * Shared legacy-style banner shown above menu landing pages.
   */
  menuHeroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Legacy-style banner displayed on menu landing pages. The gradient overlay remains applied automatically.
   */
  bannerImage?: (number | null) | Media;
  items?:
    | {
        label: string;
        href: string;
        legacyUrl?: string | null;
        openInNewTab?: boolean | null;
        /**
         * Upload one or more banners for this menu. The first image is used by default.
         */
        bannerImages?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    /**
     * Use a new line where the heading should break.
     */
    heading?: string | null;
    emphasis?: string | null;
    description?: string | null;
    primaryLabel?: string | null;
    primaryHref?: string | null;
    secondaryLabel?: string | null;
    secondaryHref?: string | null;
    sideNote?: string | null;
  };
  introduction?: {
    eyebrow?: string | null;
    /**
     * Use a new line where the heading should break.
     */
    heading?: string | null;
    emphasis?: string | null;
    description?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  services?: {
    eyebrow?: string | null;
    cards?:
      | {
          title: string;
          description?: string | null;
          linkLabel?: string | null;
          linkHref?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  newsSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    allLinkLabel?: string | null;
    allLinkHref?: string | null;
    readLabel?: string | null;
    articleLinkLabel?: string | null;
    emptyStateLabel?: string | null;
    emptyCardTitles?:
      | {
          title: string;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    eyebrow?: string | null;
    /**
     * Use a new line where the heading should break.
     */
    heading?: string | null;
    emphasis?: string | null;
    introduction?: string | null;
    phone?: string | null;
    email?: string | null;
    profileImage?: (number | null) | Media;
    profileName?: string | null;
    profileCaption?: string | null;
  };
  footer?: {
    kicker?: string | null;
    brand?: string | null;
    company?: string | null;
    /**
     * Use {year} for the current year.
     */
    copyright?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroImage?: T;
  heroImages?: T;
  menuHeroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  bannerImage?: T;
  items?:
    | T
    | {
        label?: T;
        href?: T;
        legacyUrl?: T;
        openInNewTab?: T;
        bannerImages?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        emphasis?: T;
        description?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
        sideNote?: T;
      };
  introduction?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        emphasis?: T;
        description?: T;
        linkLabel?: T;
        linkHref?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        eyebrow?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              linkLabel?: T;
              linkHref?: T;
              id?: T;
            };
      };
  newsSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        allLinkLabel?: T;
        allLinkHref?: T;
        readLabel?: T;
        articleLinkLabel?: T;
        emptyStateLabel?: T;
        emptyCardTitles?:
          | T
          | {
              title?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        emphasis?: T;
        introduction?: T;
        phone?: T;
        email?: T;
        profileImage?: T;
        profileName?: T;
        profileCaption?: T;
      };
  footer?:
    | T
    | {
        kicker?: T;
        brand?: T;
        company?: T;
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}