allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
patchedDependencies:
  '@payloadcms/drizzle@3.86.0': patches/@payloadcms__drizzle@3.86.0.patch
