allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
patchedDependencies:
  payload@3.86.0: patches/payload@3.86.0.patch
